<?php

use App\Models\Customer;
use App\Models\Order;
use App\Models\Review;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class SellerTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $this->createSeller(
            'Walmart',
            'Walmart Inc. (formerly branded as Wal-Mart Stores, Inc.) is an American multinational retail corporation that operates a chain of hypermarkets, discount department stores, and grocery stores. Headquartered in Bentonville, Arkansas, the company was founded by Sam Walton in 1962 and incorporated on October 31, 1969. It also owns and operates Sam\'s Club retail warehouses. As of January 31, 2018, Walmart has 11,718 stores and clubs in 28 countries, operating under 59 different names.The company operates under the name Walmart in the United States and Canada, as Walmart de México y Centroamérica in Mexico and Central America, as Asda in the United Kingdom, as the Seiyu Group in Japan, and as Best Price in India. It has wholly owned operations in Argentina, Chile, Brazil, and Canada.',
            'https://www.walmart.com/',
            'Bentonville, Arkansas, États-Unis',
            env('API_URL') . 'images/couverture-walmart.jpg',
            env('API_URL') . 'images/logo-walmart.jpg'
        );

        $this->createSeller(
            'Apple',
            'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. The company\'s hardware products include the iPhone smartphone, the iPad tablet computer, the Mac personal computer, the iPod portable media player, the Apple Watch smartwatch, the Apple TV digital media player, and the HomePod smart speaker.',
            'https://www.apple.com/fr/',
            'Cupertino, Californie',
            env('API_URL') . 'images/couverture-apple.jpg',
            env('API_URL') . 'images/logo-apple.jpg'
        );

        $this->createSeller(
            'Samsung',
            'Samsung was founded by Lee Byung-chul in 1938 as a trading company. Over the next three decades, the group diversified into areas including food processing, textiles, insurance, securities and retail. Samsung entered the electronics industry in the late 1960s and the construction and shipbuilding industries in the mid-1970s; these areas would drive its subsequent growth. Following Lee\'s death in 1987, Samsung was separated into four business groups – Samsung Group, Shinsegae Group, CJ Group and Hansol Group.',
            'http://samsung.com/',
            'Seocho District, Seoul, South Korea',
            env('API_URL') . 'images/couverture-samsung.jpg',
            env('API_URL') . 'images/logo-samsung.jpg'
        );

        $this->createSeller(
            'Intel',
            'Intel Corporation (stylized as intel) is an American multinational corporation and technology company headquartered in Santa Clara, California, in the Silicon Valley. It is the world\'s second largest and second highest valued semiconductor chip maker based on revenue after being overtaken by Samsung, and is the inventor of the x86 series of microprocessors, the processors found in most personal computers (PCs). Intel supplies processors for computer system manufacturers such as Apple, Lenovo, HP, and Dell.',
            'http://www.intel.com/',
            'Santa Clara, California, U.S.',
            env('API_URL') . 'images/couverture-intel.jpg',
            env('API_URL') . 'images/logo-intel.jpg'
        );

        $this->createSeller(
            'IBM',
            'International Business Machines Corporation (IBM) is an American multinational technology company headquartered in Armonk, New York, United States, with operations in over 170 countries. The company began in 1911 as the Computing-Tabulating-Recording Company (CTR) and was renamed "International Business Machines" in 1924. IBM manufactures and markets computer hardware, middleware and software, and provides hosting and consulting services in areas ranging from mainframe computers to nanotechnology. IBM is also a major research organization, holding the record for most U.S. patents generated by a business (as of 2018) for 25 consecutive years',
            'https://www.ibm.com/us-en/',
            'Armonk, New York, U.S.',
            env('API_URL') . 'images/couverture-ibm.jpg',
            env('API_URL') . 'images/logo-ibm.jpg'
        );

        $this->createSeller(
            'Nike',
            'Nike, Inc. is an American multinational corporation that is engaged in the design, development, manufacturing, and worldwide marketing and sales of footwear, apparel, equipment, accessories, and services. The company is headquartered near Beaverton, Oregon, in the Portland metropolitan area. It is the world\'s largest supplier of athletic shoes and apparel and a major manufacturer of sports equipment,',
            'http://www.nike.com/',
            'Washington County, Oregon, U.S.',
            env('API_URL') . 'images/couverture-nike.jpg',
            env('API_URL') . 'images/logo-nike.jpg'
        );

        $this->createSeller(
            'Honda',
            'Honda Motor Company, Ltd. is a Japanese public multinational conglomerate corporation primarily known as a manufacturer of automobiles, aircraft, motorcycles, and power equipment. Honda has been the world\'s largest motorcycle manufacturer since 1959, as well as the world\'s largest manufacturer of internal combustion engines measured by volume, producing more than 14 million internal combustion engines each year.',
            'http://world.honda.com/',
            'Minato, Tokyo, Japan',
            env('API_URL') . 'images/couverture-honda.jpg',
            env('API_URL') . 'images/logo-honda.jpg'
        );

        $this->createSeller(
            'Pepsi',
            'Pepsi is a carbonated soft drink manufactured by PepsiCo. Originally created and developed in 1893 by Caleb Bradham and introduced as Brad\'s Drink, it was renamed as Pepsi-Cola on August 28, 1898, and then as Pepsi in 1961.',
            'http://pepsi.com/',
            'Purchase, New York‎, US',
            env('API_URL') . 'images/couverture-pepsi.jpg',
            env('API_URL') . 'images/logo-pepsi.jpg'
        );

        $this->createSeller(
            'Loreal',
            'L\'Oréal S.A. is a French personal care company headquartered in Clichy, Hauts-de-Seine with a registered office in Paris. It is the world\'s largest cosmetics company and has developed activities in the field concentrating on hair colour, skin care, sun protection, make-up, perfume, and hair care.',
            'http://www.loreal.com/',
            'Clichy, France',
            env('API_URL') . 'images/couverture-loreal.jpg',
            env('API_URL') . 'images/logo-loreal.jpg'
        );

        $this->createSeller(
            'Ikea',
            'IKEA is a Swedish-founded multinational group that designs and sells ready-to-assemble furniture, kitchen appliances and home accessories. It has been the world\'s largest furniture retailer since at least 2008. It was founded in Sweden in 1943 by then-17-year-old Ingvar Kamprad, who was listed by Forbes in 2015 as one of the ten richest people in the world, worth more than $40 billion.',
            'http://www.ikea.com/',
            'Leiden, Netherlands',
            env('API_URL') . 'images/couverture-ikea.jpg',
            env('API_URL') . 'images/logo-ikea.jpg'
        );

        $this->createSeller(
            'Ford',
            'Ford Motor Company is an American multinational automaker headquartered in Dearborn, Michigan, a suburb of Detroit. It was founded by Henry Ford and incorporated on June 16, 1903. The company sells automobiles and commercial vehicles under the Ford brand and most luxury cars under the Lincoln brand.',
            'http://ford.com/',
            'Dearborn, Michigan, U.S.',
            env('API_URL') . 'images/couverture-ford.jpg',
            env('API_URL') . 'images/logo-ford.jpg'
        );

        $this->createSeller(
            'Zara',
            'Zara SA is a Spanish fast fashion retailer based in Arteixo in Galicia. The company was founded in 1975 by Amancio Ortega and Rosalía Mera. It is the main brand of the Inditex group, the world\'s largest apparel retailer. The fashion group also owns brands such as Massimo Dutti, Pull&Bear, Bershka, Stradivarius, Oysho, Zara Home, and Uterqüe. Zara as of 2017 manages up to 20 clothing collections a year.',
            'http://zara.com/',
            'Arteixo (A Coruña), Spain',
            env('API_URL') . 'images/couverture-zara.jpg',
            env('API_URL') . 'images/logo-zara.jpg'
        );

        $this->createSeller(
            'H&M',
            'Hennes & Mauritz AB is a Swedish multinational clothing-retail company known for its fast-fashion clothing for men, women, teenagers and children. H&M and its associated companies operate in 62 countries with over 4,500 stores and as of 2015 employed around 132,000 people. It is the second-largest global clothing retailer, just behind Spain-based Inditex.The company has a significant on-line presence, with on-line shopping available in 33 countries.',
            'http://hm.com/',
            'Stockholm, Sweden',
            env('API_URL') . 'images/couverture-hm.jpg',
            env('API_URL') . 'images/logo-hm.jpg'
        );

        $this->createSeller(
            'Netflix',
            'Netflix, Inc. is an American over-the-top media services provider, headquartered in Los Gatos, California. Founded in 1997 by Reed Hastings and Marc Randolph in Scotts Valley, California, the company\'s primary business is its subscription-based streaming service, which offers online streaming of a library of films and television programs including those produced in-house',
            'http://netflix.com/',
            'Los Gatos, California',
            env('API_URL') . 'images/couverture-netflix.jpg',
            env('API_URL') . 'images/logo-netflix.jpg'
        );

        $this->createSeller(
            'Porsche',
            'Dr.-Ing. h.c. F. Porsche AG, usually shortened to Porsche AG, is a German automobile manufacturer specializing in high-performance sports cars, SUVs and sedans. Porsche AG is headquartered in Stuttgart, and is owned by Volkswagen AG, which is itself majority-owned by Porsche Automobil Holding SE.',
            'http://www.porsche.com/',
            'Stuttgart, Baden-Württemberg, Germany',
            env('API_URL') . 'images/couverture-porsche.jpg',
            env('API_URL') . 'images/logo-porsche.jpg'
        );

        $this->createSeller(
            'Danone',
            '"Danone is a French multinational food-products corporation based in Paris and founded in Barcelona, Spain. The company is listed on Euronext Paris where it is a component of the CAC 40 stock market index. As of 2018, Danone sold products in 120 markets, and had sales in 2017 of €24.7 billion. In 2018, 29% of sales came from specialized nutrition, 19% came from waters, and 52% came from essential dairy and plant-based products."',
            'https://www.danone.com/',
            "Boulevard Haussmann 9th arrondissement, Paris, France",
            env('API_URL') . 'images/couverture-danone.jpg',
            env('API_URL') . 'images/logo-danone.jpg'
        );

        $this->createSeller(
            'Adidas',
            'Adidas AG is a multinational corporation, founded and headquartered in Herzogenaurach, Germany, that designs and manufactures shoes, clothing and accessories. It is the largest sportswear manufacturer in Europe, and the second largest in the world, after Nike. It is the holding company for the Adidas Group, which consists of the Reebok sportswear company, TaylorMade golf company (including Ashworth), Runtastic, an Austrian fitness technology company, and 8.33% of Bayern Munich, the football club.',
            'http://www.adidas-group.com/',
            "Herzogenaurach, Germany,",
            env('API_URL') . 'images/couverture-adidas.jpg',
            env('API_URL') . 'images/logo-adidas.jpg'
        );

        $this->createSeller(
            'Fedex',
            'FedEx Corporation is an American multinational courier delivery services company headquartered in Memphis, Tennessee. The name "FedEx" is a syllabic abbreviation of the name of the company\'s original air division, Federal Express (now FedEx Express), which was used from 1973 until 2000. The company is known for its overnight shipping service and pioneering a system that could track packages and provide real-time updates on package location (to help in finding lost packages), a feature that has now been implemented by most other carrier services.',
            'http://fedex.com/',
            "Memphis, Tennessee",
            env('API_URL') . 'images/couverture-fedex.jpg',
            env('API_URL') . 'images/logo-fedex.jpg'
        );

        $this->createSeller(
            'Heineken',
            'Heineken Lager Beer, or simply Heineken is a pale lager beer with 5% alcohol by volume produced by the Dutch brewing company Heineken International. Heineken is well known for its signature green bottle and red star.',
            'http://www.heineken.com/',
            "Netherlands",
            env('API_URL') . 'images/couverture-heineken.jpg',
            env('API_URL') . 'images/logo-heineken.jpg'
        );

        $this->createSeller(
            'Dell',
            'Dell is an American multinational computer technology company based in Round Rock, Texas, United States, that develops, sells, repairs, and supports computers and related products and services. Named after its founder, Michael Dell, the company is one of the largest technological corporations in the world, employing more than 103,300 people in America and around the world.',
            'https://www.dell.com/',
            "Round Rock, Texas, United States",
            env('API_URL') . 'images/couverture-dell.jpg',
            env('API_URL') . 'images/logo-dell.jpg'
        );

        $this->createSeller(
            'KFC',
            'KFC, also known as Kentucky Fried Chicken is an American fast food restaurant chain that specializes in fried chicken. Headquartered in Louisville, Kentucky, it is the world\'s second-largest restaurant chain (as measured by sales) after McDonald\'s, with almost 20,000 locations globally in 123 countries and territories as of December 2015. The chain is a subsidiary of Yum! Brands, a restaurant company that also owns the Pizza Hut, Taco Bell, and WingStreet chains.',
            'https://www.kfc.com/',
            "Louisville, Kentucky",
            env('API_URL') . 'images/couverture-kfc.jpg',
            env('API_URL') . 'images/logo-kfc.jpg'
        );

        $this->createSeller(
            'Lego',
            'Lego is a line of plastic construction toys that are manufactured by The Lego Group, a privately held company based in Billund, Denmark. The company\'s flagship product, Lego, consists of colourful interlocking plastic bricks accompanying an array of gears, figurines called minifigures, and various other parts. Lego pieces can be assembled and connected in many ways to construct objects including vehicles, buildings, and working robots. Anything constructed can then be taken apart again, and the pieces used to make other objects.',
            'http://www.lego.com/',
            "Billund, Denmark",
            env('API_URL') . 'images/couverture-lego.jpg',
            env('API_URL') . 'images/logo-lego.jpg'
        );

        $this->createSeller(
            'Lancome',
            'Lancôme is a French luxury perfumes and cosmetics house that distributes products internationally. Lancôme is part of the L\'Oréal Luxury Products division, which is its parent company and offers skin care, fragrances, and makeup.',
            'http://www.lancome.com/',
            "Paris, France",
            env('API_URL') . 'images/couverture-lancome.jpg',
            env('API_URL') . 'images/logo-lancome.jpg'
        );

        $this->createSeller(
            'Costco',
            'Costco Wholesale Corporation, trading as Costco, is an American multinational corporation which operates a chain of membership-only warehouse clubs. As of 2015, Costco was the second largest retailer in the world after Walmart, and as of 2016, Costco was the world\'s largest retailer of choice and prime beef, organic foods, rotisserie chicken, and wine.',
            'http://www.costco.com/',
            "Issaquah, Washington, United States",
            env('API_URL') . 'images/couverture-costco.jpg',
            env('API_URL') . 'images/logo-costco.jpg'
        );

        $this->createSeller(
            'Demo',
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi. Proin porttitor, orci nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl sit amet erat. Duis semper. Duis arcu massa, scelerisque vitae, consequat in, pretium a, enim. Pellentesque congue. Ut in risus volutpat libero pharetra tempor. Cras vestibulum bibendum augue. Praesent egestas leo in pede. Praesent blandit odio eu enim. Pellentesque sed dui ut augue blandit sodales. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam nibh. Mauris ac mauris sed pede pellentesque fermentum. Maecenas adipiscing ante non diam sodales hendrerit.',
            'http://www.google.com/',
            "Demo, Lille, France",
            env('API_URL') . 'images/couverture-demo.jpg',
            env('API_URL') . 'images/logo-demo.jpg',
            'testdev'
        );

    }

    public function createSeller(string $name, string $description, string $website_link, string $address, string $image_cover, string $image_profile, string $password = null)
    {
        $seller = \App\Models\Seller::firstOrCreate([
            'name' => $name,
            'image_cover' => $image_cover,
            'image_profile' => $image_profile,
            'description' => $description,
            'website_link' => $website_link,
            'phone' => 'O64242424242',
            'email' => 'contact@' . $name . '.com',
            'address' => $address,
            'verified_rating_total' => 0,
            'verified_rating_count' => 0,
            'unverified_rating_total' => 0,
            'unverified_rating_count' => 0,
        ]);

        $this->associateReviews("Fast shipping, i'm happy to order on this site.", $seller->id);
        $this->associateReviews("Excellent delivery especially during the Christmas period. No probs!!", $seller->id);
        $this->associateReviews("Very good customer service. I bought a laptop for my job and recommend to you this site.", $seller->id);
        $this->associateReviews("The Best! This site is simply one of the best online stores. I have pure trust on them. The deadlines are always correct.", $seller->id);
        $this->associateReviews("Great website, I very happy to bye a lot of things!!!", $seller->id);
        $this->associateReviews("This is the Best and big shopping site overall world.", $seller->id);
        $this->associateReviews("Buying with this site since years. They take responsibility for the goods they ship. If something goes wrong, they act right away. Great variety of good offered. I'm a very happy customer.", $seller->id);

        \App\Models\User::firstOrCreate([
            'email' => 'admin-' . $name . '@origami-review.com',
            'password' => \Illuminate\Support\Facades\Hash::make($password ? $password : uniqid()),
            'organization_id' => $seller->id,
            'organization_type' => 'App\Models\Seller'
        ]);
    }

    public function associateReviews(string $comment, $sellerId)
    {
        $marketplace = \App\Models\Marketplace::inRandomOrder()->first();
        $order = Order::create([
            'reference' => uniqid(),
            'date' => Carbon::now(),
            'marketplace_id' => $marketplace->id,
            'seller_id' => $sellerId,
            'customer_id' => Customer::all()->first()->id
        ]);

        $review = Review::create([
            'order_id' => $order->id,
            'text' => $comment,
            'criteria' => [
                [
                    'marketplace_criteria_id' => $marketplace->marketplace_criteria[0]->id,
                    'rating' => rand(3, 5)
                ],
                [
                    'marketplace_criteria_id' => $marketplace->marketplace_criteria[1]->id,
                    'rating' => rand(3, 5)
                ]
            ]
        ]);
        $review->accept();
    }
}
