version: "2"         # required to adjust maintainability checks
checks:
  similar-code:
    config:
      threshold: #overriding will affect all languages
  identical-code:
    config:
      threshold: #overriding will affect all languages